export const bodyCellData = [
  {
    id: "10847",
    english: "butterfly",
    transcription: "[ ˈbʌtəflaɪ ]",
    russian: "бабочка",
    tags: "животные",
    tags_json: '["u0436u0438u0432u043eu0442u043du044bu0435"]',
    isChanged: true,
  },
  {
    id: "10848",
    english: "hedgehog",
    transcription: "hedgehog",
    russian: "ёжик",
    tags: "",
    tags_json: "[]",
  },
  {
    id: "10853",
    english: "apple",
    transcription: "[apple]",
    russian: "яблоко",
    tags: "Array",
    tags_json: "null",
  },
  {
    id: "10854",
    english: "pear",
    transcription: "[peə]",
    russian: "груша",
    tags: "Array",
    tags_json: "null",
  },
  {
    id: "10858",
    english: "hedgehog",
    transcription: "[ ˈhedʒhɒɡ ]",
    russian: "еж",
    tags: "Array",
    tags_json: "null",
  },
  {
    id: "10862",
    english: "carrot",
    transcription: "[ˈkærət]",
    russian: "морковка",
    tags: "овощи",
    tags_json: '["u043eu0432u043eu0449u0438"]',
  },
  {
    id: "10865",
    english: "plum",
    transcription: "[plʌm]",
    russian: "слива",
    tags: "Array",
    tags_json: "null",
  },
  {
    id: "10866",
    english: "apple",
    transcription: "[apple]",
    russian: "яблоко",
    tags: "Array",
    tags_json: "null",
  },
  // {
  //   id: "10867",
  //   english: "plum",
  //   transcription: "[plʌm]",
  //   russian: "слива",
  //   tags: "Array",
  //   tags_json: "null",
  // },
  // {
  //   id: "10869",
  //   english: "carrot",
  //   transcription: "[ˈkærət]",
  //   russian: "морковка",
  //   tags: "Array",
  //   tags_json: "null",
  // },
  // {
  //   id: "10870",
  //   english: "butterfly",
  //   transcription: "[ ˈbʌtəflaɪ ]",
  //   russian: "бабочка",
  //   tags: "Array",
  //   tags_json: "null",
  // },
  // {
  //   id: "10871",
  //   english: "hedgehog",
  //   transcription: "[ ˈhedʒhɒɡ ]",
  //   russian: "еж",
  //   tags: "Array",
  //   tags_json: "null",
  // },
  // {
  //   id: "10872",
  //   english: "unicorn",
  //   transcription: "[ˈyo͞onəˌkôrn]",
  //   russian: "единорог",
  //   tags: "Array",
  //   tags_json: "null",
  // },
  // {
  //   id: "10873",
  //   english: "butterfly",
  //   transcription: "[ ˈbʌtəflaɪ ]\t",
  //   russian: "бабочка",
  //   tags: "",
  //   tags_json: '[""]',
  // },
];
